POST  http://localhost:8080/events
Content-Type: application/json
Authorization: ""

{
    "name": "test event",
    "description": "test description",
    "location": "test location",
    "date_time": "2025-01-01T15:00:00.000Z"
}