POST  http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVkbzFAYW51LmNvbSIsImV4cCI6MTc0MjU1NDY2NywidXNlcklkIjoxfQ.NKfAOHAVwyY0kNlTBg-qlKVrlelaQ62L27Iva91F0e0

{
    "name": "test event",
    "description": "test description",
    "location": "test location",
    "date_time": "2025-01-01T15:00:00.000Z"
}