POST  http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVkbzRAYW51LmNvbSIsImV4cCI6MTc0MjI4MDAyMiwidXNlcklkIjo0fQ.zeETFYKsKcYMJabWc2JRcY-yTHYVVfbPKd3kxMIinWc

{
    "name": "test event",
    "description": "test description",
    "location": "test location",
    "date_time": "2025-01-01T15:00:00.000Z"
}