POST  http://localhost:8080/events/1/register
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVkbzJAYW51LmNvbSIsImV4cCI6MTc0MjU1NTA4MSwidXNlcklkIjoyfQ.zey0mrHvwqDCF7IEs-k-94VVCw6k465KSDx7kP7hzd8
